// models/Expense.model.js
import mongoose from 'mongoose';

const expenseItemSchema = new mongoose.Schema({
  category: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ExpenseCategory',
    required: [true, 'Category is required']
  },
  description: {
    type: String,
    required: [true, 'Item description is required'],
    trim: true
  },
  quantity: {
    type: Number,
    default: 1,
    min: 0
  },
  unitPrice: {
    type: Number,
    required: [true, 'Unit price is required'],
    min: 0
  },
  amount: {
    type: Number,
    required: [true, 'Amount is required'],
    min: 0
  },
  notes: {
    type: String,
    trim: true
  },
  submittedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  submittedAt: {
    type: Date
  },
});

const expenseSchema = new mongoose.Schema({
  expenseNumber: {
    type: String,
    unique: true,
    sparse: true  // Allows null/undefined during creation - will be generated by pre-save hook
  },
  vendor: {
    type: String,
    required: [true, 'Vendor name is required'],
    trim: true
  },
  description: {
    type: String,
    required: [true, 'Expense description is required'],
    trim: true
  },
  expenseDate: {
    type: Date,
    required: [true, 'Expense date is required'],
    default: Date.now
  },
  paymentDate: {
    type: Date,
    default: null 
  },
  paymentMethod: {
    type: String,
    enum: ['mpesa', 'bank_transfer', 'cash', 'cheque', 'other'],
    required: [true, 'Payment method is required']
  },
  totalAmount: {
    type: Number,
    required: [true, 'Total amount is required'],
    min: 0
  },
  status: {
    type: String,
    enum: ['draft', 'pending', 'approved', 'paid', 'cancelled'],
    default: 'draft'
  },
  
  // Breakdown items
  items: [expenseItemSchema],
  
  // Funding sources (which income paid for this)
  fundingSources: [{
    incomeTransactionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'IncomeTransaction'
    },
    sourceType: {
      type: String,
      enum: ['fees', 'director_investment', 'grant', 'donation', 'auxiliary', 'other']
    },
    amount: {
      type: Number,
      min: 0
    },
    date: {
      type: Date,
      default: Date.now
    }
  }],
  
  // Metadata
  notes: {
    type: String,
    trim: true
  },
  attachments: [{
    filename: String,
    url: String,
    uploadedAt: Date
  }],
  
  // Tracking
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedAt: Date,
  paidBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  paidAt: Date
}, {
  timestamps: true
});

// Generate expense number before save - FIXED: Runs before validation
expenseSchema.pre('save', async function(next) {
  try {
    if (this.isNew && !this.expenseNumber) {
      const date = new Date();
      const year = date.getFullYear().toString().slice(-2);
      const month = (date.getMonth() + 1).toString().padStart(2, '0');
      
      // Get the count of existing expenses
      const Expense = mongoose.model('Expense');
      const count = await Expense.countDocuments();
      const sequence = (count + 1).toString().padStart(4, '0');
      
      this.expenseNumber = `EXP-${year}${month}-${sequence}`;
    }
    next();
  } catch (error) {
    next(error);
  }
});

// Calculate total amount from items before save
expenseSchema.pre('save', function(next) {
  if (this.items && this.items.length > 0) {
    this.totalAmount = this.items.reduce((sum, item) => sum + (item.amount || 0), 0);
  }
  next();
});

// Indexes for better query performance
// expenseSchema.index({ expenseNumber: 1 });
expenseSchema.index({ expenseDate: -1 });
expenseSchema.index({ vendor: 1 });
expenseSchema.index({ status: 1 });
expenseSchema.index({ 'items.category': 1 });

// Virtual for formatted total amount
expenseSchema.virtual('formattedTotalAmount').get(function() {
  return `KSh ${this.totalAmount?.toLocaleString() || 0}`;
});

// Virtual for formatted expense date
expenseSchema.virtual('formattedExpenseDate').get(function() {
  return this.expenseDate ? this.expenseDate.toLocaleDateString() : 'N/A';
});

// Virtual for formatted payment date
expenseSchema.virtual('formattedPaymentDate').get(function() {
  return this.paymentDate ? this.paymentDate.toLocaleDateString() : 'Not paid yet';
});

// Static method to find expenses by status
expenseSchema.statics.findByStatus = function(status) {
  return this.find({ status }).sort({ expenseDate: -1 });
};

// Static method to find expenses by vendor
expenseSchema.statics.findByVendor = function(vendor) {
  return this.find({ vendor: { $regex: vendor, $options: 'i' } }).sort({ expenseDate: -1 });
};

// Static method to get expense summary
expenseSchema.statics.getSummary = async function(startDate, endDate) {
  const matchStage = {};
  if (startDate || endDate) {
    matchStage.expenseDate = {};
    if (startDate) matchStage.expenseDate.$gte = new Date(startDate);
    if (endDate) matchStage.expenseDate.$lte = new Date(endDate);
  }
  
  const summary = await this.aggregate([
    { $match: matchStage },
    { $unwind: '$items' },
    {
      $group: {
        _id: null,
        totalAmount: { $sum: '$items.amount' },
        totalExpenses: { $sum: 1 },
        averageAmount: { $avg: '$items.amount' },
        byStatus: {
          $push: {
            status: '$status',
            amount: '$items.amount'
          }
        }
      }
    }
  ]);
  
  return summary[0] || { totalAmount: 0, totalExpenses: 0, averageAmount: 0 };
};

// Instance method to get item count
expenseSchema.methods.getItemCount = function() {
  return this.items?.length || 0;
};

// Instance method to check if expense is payable
expenseSchema.methods.isPayable = function() {
  return this.status === 'approved';
};

// Instance method to check if expense is editable
expenseSchema.methods.isEditable = function() {
  return this.status === 'draft';
};

// Instance method to check if expense is deletable
expenseSchema.methods.isDeletable = function() {
  return this.status !== 'paid';
};

const Expense = mongoose.model('Expense', expenseSchema);

export default Expense;